name: CI Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-liner script
      run: echo "Hello, World!"

    - name: List files in the repository
      run: ls -la

    - name: Display current directory
      run: pwd
